name: mnist_classifier
channels:
  - defaults
dependencies:
  - python=3.8.5
  - scikit-learn=0.23.2
  - numpy=1.19.1
  - requests=2.24.0
  - matplotlib=3.3.1
  - pytest-runner=5.2
  - python-dateutil=2.8.1
  - pillow=7.2.0
  - coverage=5.3
  - pylint=2.6.0
