name: mnist_classifier
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - coverage=4.5.4
  - scikit-learn=0.23.2
  - numpy=1.19.1
  - requests=2.24.0
  - matplotlib=3.3.1
  - pytest-runner=5.2
  - python-dateutil=2.8.1
  - pillow=7.2.0
  - pylint=2.6.0
  - python-coveralls=2.9.3
  - sphinx=3.2.1=py_0
  - pip:
    - sphinx-rtd-theme==0.5.0
    - ghp-import
