version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            conda env create -f environment.yml
      
      - run:
          command: |
            conda activate mnist_classifier
            python ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
