version: 2.1

jobs:
  build-and-test:
    docker:
      - image: continuumio/miniconda3
   
    steps:
      - checkout
            
      - run:
          name: install dependencies
          command: |
            conda env create -f environment.yml

      - run:
          name: Run linter
          command: |
            source activate mnist_classifier
            pylint --output-format=colorized *.py src/ tests/
      
      - run:
          command: |
            source activate mnist_classifier
            coverage run --source src -m unittest discover
            coverage report
            coverage html 
            coveralls
          name: Test

      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - build-and-test
