version: 2.1

general:
  branches:
    ignore:
      - gh-pages

jobs:
  test:
    docker:
      - image: continuumio/miniconda3
   
    steps:
      - checkout
            
      - run:
          name: install dependencies
          command: |
            conda env create -f environment.yml

      - run:
          name: Run linter
          command: |
            source activate mnist_classifier
            pylint --output-format=colorized *.py mnist_classifier/ tests/
      
      - run:
          command: |
            source activate mnist_classifier
            coverage run --source mnist_classifier -m unittest discover
            coverage report
            coverage html
            coveralls
          name: Test

      - store_artifacts:
          path: htmlcov

  deploy-docs:
    docker:
      - image: python:3.6

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "ea:b2:4f:55:9f:41:22:c5:7c:9f:b9:b1:91:e1:64:59"
            
      - run:
          name: install dependencies
          command: |
            pip install sphinx sphinx-rtd-theme ghp-import
      
      - run:
          name: Build and deploy
          command: |
            sphinx-build doc sphinx
            ghp-import -m "Update docs [ci skip]" --no-jekyll sphinx/
            git config user.email "ci-build@chrissandrini.ch"
            git config user.name "ci-build"
            git push origin gh-pages
  
  build-and-deploy:
    docker:
      - image: continuumio/miniconda3
   
    steps:
      - checkout
            
      - run:
          name: Install dependencies
          command: |
            conda env create -f environment.yml
      
      - run:
          name: Verify tag
          command: |
            source activate mnist_classifier
            #python setup.py verify
      
      - run:
          name: Create package
          command: |
            source activate mnist_classifier
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
            python setup.py sdist bdist_wheel

      - run:
          name: Upload package to pypi
          command: |
            source activate mnist_classifier
            twine upload dist/*
      
            

workflows:
  main:
    jobs:
      - test
      - deploy-docs:
          requires:
            - test
          
          filters:
            branches:
              only:
                - master

      - build-and-deploy:
          requires:
            - test