version: 2.1

jobs:
  build-and-test:
    docker:
      - image: continuumio/miniconda3
   
    steps:
      - checkout
            
      - run:
          name: install dependencies
          command: |
            conda env create -f environment.yml
      
      - run:
          command: |
            source activate mnist_classifier
            python -m unittest discover tests
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
